#### general settings
name: Scshield_Train

nbit: 64

train_config:
  output_dir: exps
  logging_dir: logs
  
  learning_rate: 1e-4
  weight_decay: 1e-2
  lr_scheduler: cosine
  lr_warmup_steps: 5000
  num_training_steps: 1000000

  with_degrade: True

  all_step: 1000000

  use_jnd: True
  jnd_step: 50000



log:
  # log_step: 2
  # view_step: 5
  # val_step: 5
  # save_step: 10
  log_step: 100
  view_step: 5000
  val_step: 5000
  save_step: 10000

#### datasets
datasets:
  train:
    img_path: /data02/shizhihao/datasets/coco/train2017
    ann_file: /data02/shizhihao/datasets/coco/annotations/instances_train2017.json
    image_size: 512
    data_len: -1
    use_shuffle: true
    n_workers: 2
    batchsize: 2
  
  val:
    img_path: /data02/shizhihao/datasets/coco/val2017
    ann_file: /data02/shizhihao/datasets/coco/annotations/instances_val2017.json
    image_size: 512
    data_len: 100
    shuffle: false
    n_workers: 1
    batchsize: 1


#### network structures
model:
  sec_emb_config:
    nbit: 64
    embed_dim: 768
    sec_p_dim: 3

  wm_enc_config:
    img_size: 512
    width: 512
    height: 512
    patch_size: 16
    num_patches: 1024
    in_channels: 3
    sec_p_dim: 3
    hidden: 768
    depth: 12
    heads: 12
    mlp_ratio: 4.0
    nbit: 64
    dropout:  0.0
    pos_embed_type: sincos  # "sincos" or "learned"
    scale: 1.0              # 缩放位置坐标
    extra_tokens: 0           # 预留额外token数

  wm_dec_config:
    img_size: 512
    width: 512
    height: 512
    patch_size: 16
    num_patches: 1024
    in_channels: 3
    out_channels: 8
    hidden: 768
    depth: 12
    heads: 12
    mlp_ratio: 4.0
    nbit: 64
    dropout: 0.0
    pos_embed_type: sincos   # "sincos" or "learned"
    scale: 1.0           # 缩放位置坐标
    extra_tokens: 0            # 预留额外token数
    use_cls_token: True
    use_learn_bit_probe: True

masks:
  invert_proba: 0.5
  irregular_proba: 0.25
  box_proba: 0.25
  full_proba: 0.25
  segm_proba: 0.25

stage:
  stage1: 10000
  stage2: 20000
  stage3: 100000
  # stage1: 10
  # stage2: 20
  # stage3: 50

#### path
loss:
  img_loss_weight:
    start: 1.0
    end: 1.0
    decay_steps: 10000

  img_lpips_loss_weight:
    start: 0.0
    end: 0.5
    decay_steps: 100000

  sec_loss_weight:
    start: 20.0
    end: 0.25
    decay_steps: 200000

  sec_patch_weight_loss_weight:
    start: 0.0
    end: 0.5
    decay_steps: 20000

  mask_loss_weight:
    start: 10
    end: 0.2
    decay_steps: 200000

  edge_loss_weight:
    start: 10.0
    end: 1.0     # 不变
    decay_steps: 200000


path:
  pretrain_model_G: #/data02/shizhihao/Work/watermarknew/experiments/train_base/models/85000_G.pth
  models: ckp/base
  strict_load: true
  resume_state: #experiments/train_base/training_state/85000.state


#### training settings: learning rate scheme, loss

