#### general settings
name: Scshield_Train

nbit: 64

train_config:
  output_dir: exps/expsv1samll_patch1
  logging_dir: logs
  
  learning_rate: 1e-4
  weight_decay: 1e-2
  lr_scheduler: cosine
  lr_warmup_steps: 5000
  num_training_steps: 1000000

  with_degrade: True

  all_step: 1000000

  use_jnd: True
  jnd_step: 10000



log:
  # log_step: 5
  # view_step: 10
  # val_step: 10
  # save_step: 20
  log_step: 100
  view_step: 500
  val_step: 1000
  save_step: 10000

#### datasets
datasets:
  train:
    img_path: /data02/shizhihao/datasets/coco/train2017
    ann_file: /data02/shizhihao/datasets/coco/annotations/instances_train2017.json
    image_size: 512
    data_len: 2000
    use_shuffle: true
    n_workers: 2
    batchsize: 2
  
  val:
    img_path: /data02/shizhihao/datasets/coco/val2017
    ann_file: /data02/shizhihao/datasets/coco/annotations/instances_val2017.json
    image_size: 512
    data_len: 100
    shuffle: false
    n_workers: 1
    batchsize: 1


#### network structures
model:
  sec_emb_config:
    nbit: 64
    embed_dim: 768
    mode: simple_mlp
    return_patch_feat: true


  wm_enc_config:
    img_size: 512
    width: 512
    height: 512
    patch_size: 16
    num_patches: 1024
    in_channels: 3
    sec_p_dim: 0
    hidden: 768
    depth: 8
    heads: 12
    mlp_ratio: 4.0
    nbit: 64
    dropout:  0.0
    pos_embed_type: sincos  # "sincos" or "learned"
    scale: 1.0              # 缩放位置坐标
    extra_tokens: 0           # 预留额外token数

  sec_dec_config:
    img_size: 512
    width: 512
    height: 512
    patch_size: 16
    num_patches: 1024
    in_channels: 3
    out_channels: 8
    hidden: 768
    depth: 8
    heads: 12
    mlp_ratio: 4.0
    nbit: 64
    dropout: 0.0
    pos_embed_type: sincos   # "sincos" or "learned"
    scale: 1.0           # 缩放位置坐标
    extra_tokens: 0            # 预留额外token数
    use_cls_token: false
    use_learn_bit_probe: True

  mask_dec_config:
    depth: [5, 8, 20, 7] # [3, 4, 10, 4]
    embed_dim: [64, 128, 320, 512]
    head_dim: 64
    img_size: 512
    s_blocks3: [8, 4, 2, 1]
    s_blocks4: [2, 1]
    mlp_ratio: 4



masks:
  invert_proba: 0.5
  irregular_proba: 0.25
  box_proba: 0.25
  full_proba: 0.25
  segm_proba: 0.25

mask2s:
  invert_proba: 0.5
  irregular_proba: 0.15
  box_proba: 0.15
  full_proba: 0.5
  segm_proba: 0.2

stage:
  stage1: 10000
  stage2: 20000
  stage3: 100000
  # stage1: 10
  # stage2: 20
  # stage3: 50

#### path
loss:
  img_loss_weight:
    start: 1.0
    end: 1.0
    decay_steps: 10000

  img_lpips_loss_weight:
    start: 0.0
    end: 0.5
    decay_steps: 100000

  sec_loss_weight:
    start: 25.0
    end: 0.25
    decay_steps: 150000

  sec_patch_weight_loss_weight:
    start: 0.5
    end: 0.1
    decay_steps: 50000

  mask_loss_weight:
    start: 5 # 5 #10
    end: 0.2 #0.2 #0.2
    decay_steps: 150000

  edge_loss_weight:
    start: 5 #5 # 10.0
    end: 0.5 #0.5 # 1.0     # 不变
    decay_steps: 150000


path:
  pretrain_model_G: #/data02/shizhihao/Work/watermarknew/experiments/train_base/models/85000_G.pth
  models: ckp/base
  strict_load: true
  resume_state: #experiments/train_base/training_state/85000.state


#### training settings: learning rate scheme, loss

